
name: Wade Huang
title: Wade Huang's Blog
email: wadehuang36@gmail.com
description: >
  A technology enthusiast. <br/>
  Expert at .Net, Nodejs, Angular and Android
selfie: /assets/images/wade.jpg
baseurl: ""
url: "https://wadehuang36.github.com"
github:  wadehuang36
linkedin:  wadehuang

markdown: kramdown

paginate: 10

paginate_path: "/page:num/"

disqus:
  shortname: wadeblog

google-analytics: 'UA-101876196-1'
google-cse: '000081450704203220197:elblxastjvi'

gems:
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - dist
